import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "surface-container-low": "#f0f5ed",
        "primary-fixed": "#acf4a4",
        "on-secondary-fixed": "#002204",
        "on-primary-fixed": "#002203",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c0c9bb",
        "primary-container": "#1b5e20",
        "on-secondary": "#ffffff",
        outline: "#717a6d",
        error: "#ba1a1a",
        "on-tertiary-fixed": "#001d34",
        "on-primary-fixed-variant": "#0c5216",
        "tertiary-fixed": "#cfe5ff",
        "tertiary-fixed-dim": "#99cbff",
        "secondary-fixed-dim": "#6ede70",
        "on-tertiary-container": "#95c9ff",
        "on-surface": "#171d18",
        "primary-fixed-dim": "#91d78a",
        "surface-container": "#eaf0e7",
        "inverse-surface": "#2c322c",
        surface: "#f5fbf2",
        secondary: "#006e1c",
        "surface-dim": "#d6dcd3",
        "on-tertiary-fixed-variant": "#004a78",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-high": "#e4eae1",
        "secondary-fixed": "#8afb89",
        "on-primary-container": "#90d689",
        primary: "#00450d",
        "on-surface-variant": "#41493e",
        "on-background": "#171d18",
        "on-tertiary": "#ffffff",
        "surface-tint": "#2a6b2c",
        "surface-container-highest": "#dee4dc",
        "surface-variant": "#dee4dc",
        "inverse-primary": "#91d78a",
        "on-secondary-container": "#00731e",
        "tertiary-container": "#005589",
        "on-error-container": "#93000a",
        tertiary: "#003d65",
        "on-secondary-fixed-variant": "#005313",
        background: "#f5fbf2",
        "secondary-container": "#87f886",
        "surface-bright": "#f5fbf2",
        "inverse-on-surface": "#edf2ea",
      },
      fontFamily: {
        headline: ["var(--font-plus-jakarta)"],
        body: ["var(--font-inter)"],
        label: ["var(--font-inter)"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
